default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: solidqueue_example
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: solidqueue_example_development

test:
  <<: *default
  database: solidqueue_example_test

production:
  <<: *default
  database: solidqueue_example_production
  username: solidqueue_example
  password:
